version: "3.9"
services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=paulotech
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/var/lib/postgresql/data