spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_tech
    username: postgres
    password: Paulo99#
    driver-class-name: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    enable-lazy-loading: true

  liquibase:
    change-log: classpath:/db/changelog/master.xml
    default-schema: ecommerce_tech
    contexts: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://paulotech.kinde.com
          jwk-set-uri: https://paulotech.kinde.com/.well-known/jwks
          audiences: http://localhost:8080/api

  application:
    name: EcommerceBackend

  server:
    port: 8080

    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: "*"
      allowed-headers: "*"
      exposed-headers: "*"
      allow-credentials: false
      max-age: 300

  kinde:
    api: http://paulotech.kinde.com
    client-id: ${KINDE_CLIENT_ID}
    client-secret: ${KINDE_SECRET_KEY}
    audience: https://paulotech.kinde.com/api
